//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gest_Cinel_2.Pages.Backend_Pages.Pages
{


    public partial class test_backend
    {
    }
}
